name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      - master

# Cấp quyền ghi để cho phép hành động đẩy trang tĩnh lên nhánh gh-pages
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Node.js ⚙️
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install and Build 🔧
        run: |
          npm install
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # Thư mục sau khi build Vite sẽ phân phối
          branch: gh-pages # Nhánh đích lưu trữ trang tĩnh của GitHub Pages
          clean: true
